Ready to build data set
alexandrainst/NordjyllandNews pull request #1
Opened 2023-02-06 11:51 UTC by oliverkinch

2023-02-06 12:54 UTC, saattrupdan commented
Generel kommentar:

Vi skelner mellem Python _moduler_ og Python _scripts_. Begge er `py` filer, men et Pythonmodul indeholder funktioner/klasser, som vi gerne vil importere andetsteds, hvor et Pythonscript skal kunne køres fra terminalen, og har ét formål (såsom at bygge et datasæt). I repo'et indeholder `src/nordjylland_news` alle modulerne og `src/scripts` alle scripts.

Jeg vil derfor foreslå, at du omstrukturerer dine filer således:

- `constants.py` flyttes til `nordjylland_news`, da det er et modul
- `main.py` er rigtig nok et script, men jeg ville omdøbe det, så det er klart, hvad den gør. Du kunne fx kalde den `build_summarization_dataset.py`
- `summary_data_set.py` er et modul og flyttes til `nordjylland_news`
- `utils.py` er også et modul og flyttes altså også til `nordjylland_news`

Jeg får lige kigget ordentligt på koden når de lige er flyttet rundt på 🙂

2023-02-06 14:54 UTC, oliverkinch commented
Filerne er nu flyttet og alle tests i CI godkendt (ikke helt sikker på hvordan de blev godkendt i første commit? 🧐)

2023-02-08 18:01 UTC, saattrupdan requested changes
Det ser rigtig fint ud! Der er lige nogle generelle pointer, som går igen:

1. Husk på at dokumentere din kode med docstrenge, kommentarer og type hints. Du gør det de fleste steder, som er super, men det har glippet nogle få steder.
2. Modul-docstrenge i toppen af dine moduler og scripts er en rigtig god idé, da det giver andre udviklere et meget hurtigt overblik over kodebasen. Jeg har skrevet nogle eksempler på disse her.
3. Logging er generelt bedre at bruge end print statements, da andre udviklere, og brugere, kan slå dem fra, hvis de ikke skal bruge dem. Men det kan vi evt. kigge på senere.

Kan du give det et skud mere? 🙂

2023-02-08 18:01 UTC, saattrupdan commented on pyproject.toml
> +bs4 = "^0.0.1"
Jeg vil foreslå, at du tilføjer `beautifulsoup4` i stedet for `bs4`, da sidstnævnte er en mærkelig wrapper, som altid er version 0.0.1 (det samme er tilfældet med `sklearn` vs `scikit-learn`, fx).

2023-02-08 18:01 UTC, saattrupdan commented on src/nordjylland_news/summary_data_set.py
> +from nordjylland_news.utils import append_jsonl, html_to_text, init_jsonl, load_jsonl
Det er bedst at importere andre moduler direkte fra andre moduler, som relative imports, fremfor at importere dem eksternt som du gør her. Altså burde dette ændres til:

```suggestion
from .constants import HEADERS, MAX_PER_PAGE, RAW_DATA_PATH
from .utils import append_jsonl, html_to_text, init_jsonl, load_jsonl
```

Bemærk dog, at i *scripts* skal vi importere ting eksternt, med absolutte imports. Det er bare når man importerer moduler fra andre moduler, at vi gør det relativt.

2023-02-08 18:01 UTC, saattrupdan commented on src/nordjylland_news/summary_data_set.py
> +        """Gets seen uuids
```suggestion
        """Gets seen uuids.
```

2023-02-08 18:01 UTC, saattrupdan commented on src/nordjylland_news/summary_data_set.py
> +        """Gets seen uuids
Derudover, måske kan du skrive hvad "seen uuids" betyder?

2023-02-08 18:01 UTC, saattrupdan commented on src/nordjylland_news/summary_data_set.py
> +    def get_seen_uuids(self):
```suggestion
    def get_seen_uuids(self) -> Set[str]:
```

2023-02-08 18:01 UTC, saattrupdan commented on src/nordjylland_news/summary_data_set.py
> +    def get_seen_uuids(self):
NB: Dette kræver lige at du også importerer `Set` fra `typing` pakken.

2023-02-08 18:01 UTC, saattrupdan commented on src/nordjylland_news/summary_data_set.py
> +            sleep (int): Number of seconds to sleep between each page
```suggestion
            sleep (int, optional): 
                Number of seconds to sleep between each page. Defaults
                to 30 seconds.
```

2023-02-08 18:01 UTC, saattrupdan commented on src/nordjylland_news/summary_data_set.py
> +            total_articles (int): Total number of articless to get
Lille typo.

```suggestion
            total_articles (int): 
                Total number of articles to get.
```

2023-02-08 18:01 UTC, saattrupdan commented on src/nordjylland_news/summary_data_set.py
> +            )
Generelt set er det bedre at bruge `logging` modulet fremfor at bruge `print` direkte, da det giver brugerne mulighed for at fjerne logging beskederne. Men lad os tage det i en separat PR 🙂

2023-02-08 18:01 UTC, saattrupdan commented on src/nordjylland_news/summary_data_set.py
> +        """
Mangler `Returns:` blok i docstrengen.

2023-02-08 18:01 UTC, saattrupdan commented on src/nordjylland_news/summary_data_set.py
> +                            return None
Mangler en masse kommentarer her. Hvad sker der i de forskellige kodeblokke?

2023-02-08 18:01 UTC, saattrupdan commented on src/nordjylland_news/summary_data_set.py
> +    def get_uuid(article: dict):
```suggestion
    def get_uuid(article: dict) -> str:
```

2023-02-08 18:01 UTC, saattrupdan commented on src/nordjylland_news/summary_data_set.py
> +    def get_page_with_articles_data(page: int):
```suggestion
    def get_page_with_articles_data(page: int) -> list:
```

2023-02-08 18:01 UTC, saattrupdan commented on src/nordjylland_news/summary_data_set.py
> +        return text.strip()
Hvad gør denne? Mangler kommentarer og en docstreng.

2023-02-08 18:01 UTC, saattrupdan commented on src/nordjylland_news/summary_data_set.py
> +    def get_summary(article: dict):
```suggestion
    def get_summary(article: dict) -> str:
```

2023-02-08 18:01 UTC, saattrupdan commented on src/nordjylland_news/summary_data_set.py
> +import os
Det plejer at være god stil at have en modul-docstreng i toppen af hvert modul, som kort beskriver hvad modulet indeholder. Det kommer også automatisk med i dokumentationen.
```suggestion
"""Class that builds and contains the summarisation dataset."""

import os
```

2023-02-08 18:01 UTC, saattrupdan commented on src/nordjylland_news/utils.py
> +import jsonlines
Igen, en modul-docstreng er god stil.
```suggestion
"""Utility functions and classes to be used throughout the project."""

import jsonlines
```

2023-02-08 18:01 UTC, saattrupdan commented on src/nordjylland_news/utils.py
> +def init_jsonl(file_name: str):
```suggestion
def init_jsonl(file_name: str) -> None:
```

2023-02-08 18:01 UTC, saattrupdan commented on src/nordjylland_news/utils.py
> +    """Initializes jsonl file
Hvad gør denne her helt præcist? Laver filen?

2023-02-08 18:01 UTC, saattrupdan commented on src/nordjylland_news/utils.py
> +def append_jsonl(data: list, file_name: str):
```suggestion
def append_jsonl(data: list, file_name: str) -> None:
```

2023-02-08 18:01 UTC, saattrupdan commented on src/nordjylland_news/utils.py
> +            Data to append
Mangler `file_name`.
```suggestion
    Args:
        data (list):
            Data to append
        file_name (str):
            The name of the JSONL file where the data should be appended.
```

2023-02-08 18:01 UTC, saattrupdan commented on src/nordjylland_news/utils.py
> +def load_jsonl(file_name: str):
```suggestion
def load_jsonl(file_name: str) -> List[dict]:
```

2023-02-08 18:01 UTC, saattrupdan commented on src/nordjylland_news/utils.py
> +        list:
```suggestion
        list of dict:
```

2023-02-08 18:01 UTC, saattrupdan commented on src/nordjylland_news/utils.py
> +def html_to_text(html: str):
```suggestion
def html_to_text(html: str) -> str:
```

2023-02-08 18:01 UTC, saattrupdan commented on src/scripts/build_summarization_dataset.py
> +import argparse
Det her er ikke et modul, men en modul-docstring er stadig rigtig god stil. Når det kommer til scripts, kan man derudover også skrive hvordan man kalder scriptet:

```suggestion
"""Script that builds the summarisation dataset.

Usage:
    >>> python src/scripts/build_summarization_dataset.py
    
    We can also specify the total number of articles, that we want to process (default is 500):
    >>> python src/scripts/build_summarization_dataset.py --total_articles 100
""""

import argparse
```

2023-02-10 15:17 UTC, oliverkinch commented
> Det ser rigtig fint ud! Der er lige nogle generelle pointer, som går igen:
> 
> 1. Husk på at dokumentere din kode med docstrenge, kommentarer og type hints. Du gør det de fleste steder, som er super, men det har glippet nogle få steder.
> 2. Modul-docstrenge i toppen af dine moduler og scripts er en rigtig god idé, da det giver andre udviklere et meget hurtigt overblik over kodebasen. Jeg har skrevet nogle eksempler på disse her.
> 3. Logging er generelt bedre at bruge end print statements, da andre udviklere, og brugere, kan slå dem fra, hvis de ikke skal bruge dem. Men det kan vi evt. kigge på senere.
> 
> Kan du give det et skud mere? 🙂

Jeg har nu prøvet at inkludere alt hvad du nævner her (undtagen delen med printing/logging) :)

2023-02-10 19:00 UTC, saattrupdan requested changes
Så er vi næsten i mål! Meget få stilistiske ændringer, og så skulle den være der :)

2023-02-10 19:00 UTC, saattrupdan commented on src/nordjylland_news/summary_data_set.py
> +            None
Normalt udelades "Returns" blokken i docstrengen, hvis der ikke returneres noget.

```suggestion
```

2023-02-10 19:00 UTC, saattrupdan commented on src/scripts/build_summarization_dataset.py
> +Usage:
```suggestion
"""Script that builds the summarisation dataset.

Usage:
```

2023-02-10 19:28 UTC, oliverkinch commented
Sådaaan - så er jeg vist også ved at have styr på stilen 😎

2023-02-10 20:01 UTC, saattrupdan approved these changes
LGTM!

2023-02-16 13:32 UTC, merged