Ready to build image caption data set.
alexandrainst/NordjyllandNews pull request #2
Opened 2023-02-17 13:55 UTC by oliverkinch

image_caption_data_set.py indeholder class til at bygge image caption dataset.

build_image_caption_dataset.py er scriptet der skal køres, for at bygge image caption dataset.

Indeholder også minor ændringer til summary_data_set.py i hensyn til ændringer lavet i constants.py og utils.py, men det burde ikke være noget, som kræver det store code review.

2023-02-17 14:02 UTC, oliverkinch commented
Hvorfor fejler "black" her? 🧐 Det må blive efter weekenden, at jeg opklarer det mysterie. 

<img width="460" alt="image" src="https://user-images.githubusercontent.com/71556498/219676074-25e1ab73-71dd-405d-9985-5a7f3767d1a6.png">

2023-02-20 10:59 UTC, saattrupdan requested changes
Ser supergodt ud! Jeg har kun et par få kommentarer. Kommentaren omkring configs kan vi lige tage sammen.

2023-02-20 10:59 UTC, saattrupdan commented on src/nordjylland_news/constants.py
> +SLEEP_15_MINUTES = 900
De fleste af disse constants passer nok bedre i en config fil. Vi kan lige snakke om det når du er her.

2023-02-20 10:59 UTC, saattrupdan commented on src/nordjylland_news/utils.py
> +def send_request(url):
```suggestion
def send_request(url) -> dict:
```

2023-02-20 10:59 UTC, saattrupdan commented on src/nordjylland_news/utils.py
> +    """
Mangler beskrivelse.

2023-02-20 15:12 UTC, AJDERS commented
@oliverkinch , @saattrupdan har travlt, så jeg reviewer osv. indtil han har mindre travlt :) Du kan fange mig til en snak om config, tests, og logging når det passer dig :)

2023-02-21 07:29 UTC, AJDERS commented
Jeg er ikke sikker på hvordan det er sket, men linting checket fejler. Du kan køre: `black .`, som burde fikse det :)

2023-02-22 10:56 UTC, oliverkinch commented
En lidt stor omgang. Jeg kan eventuelt lige sidde med, når du kigger det igennem? @AJDERS

2023-02-23 13:22 UTC, AJDERS commented
> En lidt stor omgang. Jeg kan eventuelt lige sidde med, når du kigger det igennem? @AJDERS

Yup 100%, lad os gøre det fredag. Vil du lige markere om rettelserne ovenfor er resolved eller ej?

2023-02-23 20:16 UTC, oliverkinch commented
> > En lidt stor omgang. Jeg kan eventuelt lige sidde med, når du kigger det igennem? @AJDERS
> 
> Yup 100%, lad os gøre det fredag. Vil du lige markere om rettelserne ovenfor er resolved eller ej?

Jeg har ligget syg i dag, så tror jeg bør holde mig fra kontoret i morgen. Kan vi tage den mandag?

2023-02-27 10:37 UTC, oliverkinch commented on src/nordjylland_news/base_dataset_class.py
> +        self.logger = logging.getLogger(__name__)
Skift __name__ til self.dataset_name

2023-02-27 10:44 UTC, oliverkinch commented on src/nordjylland_news/constants.py
> +SLEEP_LONG = 900  # 15 minutes
Smid disse i config.yaml

2023-02-27 11:48 UTC, oliverkinch commented
Så skulle ændringerne, som vi (@saattrupdan) snakkede om tidligere, være ordnet :)

2023-02-27 13:38 UTC, saattrupdan requested changes
Meget lille ændring, og ellers ser det helt fint ud!

2023-02-27 13:38 UTC, saattrupdan commented on src/nordjylland_news/image_caption_dataset.py
> +        super().__init__(dataset_name=dataset_name, cfg=cfg)
Dette sker helt automatisk, da argumenterne til baseklassen er de samme. Så du kan sagtens fjerne hele denne her init metode 🙂

2023-02-27 14:28 UTC, saattrupdan approved these changes
LGTM! 🎉

2023-02-27 16:59 UTC, merged